name: CI

on: [push]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Test swiftbox and update VERSION
      run: |
        chmod +x swiftbox.sh
        VERSION=`./swiftbox.sh version`
        if [ $? -eq 0 ]
        then
          if [ $VERSION = `cat VERSION` ]
          then
            exit 0
          else
            echo $VERSION > VERSION
            git config --global user.name  "${{ github.actor }}"
            git config --global user.email "`curl https://api.github.com/users/${{ github.actor }} | jq .email`"
            git commit -m "Release $VERSION" -a
            git tag -a "v$VERSION" -m "Release $VERSION"
          fi
        else
          exit 1
        fi
      shell: bash
        
    - name: Push to GitHub
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  test-ubuntu:
    runs-on: ubuntu-18.04
    needs: tag
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test swiftbox version
      run: |
        chmod +x swiftbox.sh
        ./swiftbox.sh version

    - name: Test swiftbox lookup
      run: ./swiftbox.sh lookup 5.1.5

    - name: Test swiftbox get with sudo
      run: |
        sudo ./swiftbox.sh get 5.1.2
        source /etc/environment
        source /etc/profile.d/swiftbox.sh
        which swift
        swiftc -v

    - name: Test swiftbox get
      run: |
        ./swiftbox.sh get 5.2
        ./swiftbox.sh get 5.1.5
        source /etc/environment
        source $HOME/.swiftbox/env.sh
        swiftc -v

    - name: Test swiftbox list and use
      run: |
        ./swiftbox.sh list
        sudo ./swiftbox.sh list
        ./swiftbox.sh use 5.1.5
        ./swiftbox.sh list
        source /etc/environment
        source $HOME/.swiftbox/env.sh
        swiftc -v

    - name: Test swiftbox clean
      run: |
        ./swiftbox.sh clean
        sudo ./swiftbox.sh clean

    - name: Test swiftbox remove
      run: |
        sudo ./swiftbox.sh remove 5.1.2
        ./swiftbox.sh remove 5.1.5
        ./swiftbox.sh use 5.2

    - name: Test Swift status
      run: |
        source /etc/environment
        source $HOME/.swiftbox/env.sh
        echo "\$PATH=$PATH"
        which swift
        swiftc -v

    - name: Test Swift compiler
      run: |
        source /etc/environment  
        source $HOME/.swiftbox/env.sh
        swift test.swift
        swiftc test.swift -o test && ./test

    - name: Test swiftbox close
      run: ./swiftbox.sh close

    - name: Test Swift disabled
      run: |
        source /etc/environment
        source $HOME/.swiftbox/env.sh
        if [ `which swift` != /usr/* ]
        then
          exit 1
        fi

    - name: Test swiftbox install and update
      run: |
        sh -c "$(curl -fsSL https://cdn.jsdelivr.net/gh/stevapple/swiftbox@`./swiftbox.sh version`/install.sh)"
        swiftbox version
        swiftbox update

  test-centos:
    needs: tag
    container:
      image: centos:8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install tools
      run: yum install curl -y

    - name: Test swiftbox version
      run: |
        chmod +x swiftbox.sh
        ./swiftbox.sh version

    - name: Test swiftbox install and update
      run: |
        sh -c "$(curl -fsSL https://cdn.jsdelivr.net/gh/stevapple/swiftbox@`./swiftbox.sh version`/install.sh)"
        swiftbox version
        swiftbox update