name: CI

on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-18.04
    env:
      MAINVER: "5.2.4"
      ALTVER: "5.1.5"
    defaults:
      run:
        shell: bash --login -eo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test swiftbox version
      run: |
        chmod +x swiftbox.sh
        ./swiftbox.sh version

    - name: Test swiftbox install
      run: ./swiftbox.sh install

    - name: Test swiftbox lookup
      run: swiftbox lookup $MAINVER

    - name: Test swiftbox get with sudo
      run: |
        sudo swiftbox get $MAINVER
        source /etc/environment && source /opt/swiftbox/env.sh
        if [ `which swift` != "/opt/swiftbox/toolchain/swift-$MAINVER/usr/bin/swift" ]
        then
          echo "::error::Swift $MAINVER is not installed correctly."
          exit 2
        fi
        swiftc -v

    - name: Test swiftbox get
      run: |
        swiftbox get $MAINVER
        swiftbox get $ALTVER
        source /etc/environment && source /opt/swiftbox/env.sh && source $HOME/.swiftbox/env.sh
        if [ `which swift` != "$HOME/.swiftbox/toolchain/swift-$MAINVER/usr/bin/swift" ]
        then
          echo "::error::Swift $MAINVER is not installed correctly."
          exit 2
        fi
        swiftc -v

    - name: Test swiftbox list and use
      run: |
        swiftbox list
        sudo swiftbox list
        swiftbox use $ALTVER
        source /etc/environment && source /opt/swiftbox/env.sh && source $HOME/.swiftbox/env.sh
        swiftbox list
        if [ `which swift` != "$HOME/.swiftbox/toolchain/swift-$ALTVER/usr/bin/swift" ]
        then
          echo "::error::Swift $ALTVER is not selected correctly."
          exit 2
        fi
        swiftc -v

    - name: Test swiftbox clean
      run: |
        swiftbox clean
        sudo swiftbox clean

    - name: Test swiftbox remove
      run: |
        sudo swiftbox remove $MAINVER
        swiftbox remove $ALTVER
        swiftbox use $MAINVER

    - name: Test Swift status
      run: |
        echo "\$PATH=$PATH"
        if [ `which swift` != "$HOME/.swiftbox/toolchain/swift-$MAINVER/usr/bin/swift" ]
        then
          echo "::error::Swift $ALTVER is not removed correctly."
          exit 2
        fi
        swiftc -v

    - name: Test Swift compiler
      run: |
        swift test.swift
        swiftc test.swift -o test && ./test

    - name: Test swiftbox close
      run: swiftbox close

    - name: Test Swift disabled
      run: |
        if [ `which swift` != /usr/* ]
        then
          echo "::error::swiftbox is not closed correctly."
          exit 1
        fi

  test-ubuntu-nightly:
    container:
      image: ubuntu:20.04
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --login -eo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test swiftbox version
      run: |
        chmod +x swiftbox.sh
        ./swiftbox.sh version

    - name: Test swiftbox lookup nightly
      run: ./swiftbox.sh lookup nightly

    - name: Test swiftbox get nightly
      env:
        DEBIAN_FRONTEND: noninteractive
        DEBCONF_NONINTERACTIVE_SEEN: true
      run: ./swiftbox.sh get nightly

    - name: Test Swift status
      run: |
        echo "\$PATH=$PATH"
        ./swiftbox.sh list
        which swift
        swiftc -v

    - name: Test Swift compiler
      run: |
        swift test.swift
        swiftc test.swift -o test && ./test

  test-centos-nightly:
    container:
      image: centos:8
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --login -eo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test swiftbox version
      run: |
        chmod +x swiftbox.sh
        ./swiftbox.sh version
    
    - name: Test swiftbox lookup nightly
      run: ./swiftbox.sh lookup nightly

    - name: Test swiftbox get nightly
      run: ./swiftbox.sh get nightly

    - name: Install which
      run: yum install which -y

    - name: Test Swift status
      run: |
        echo "\$PATH=$PATH"
        ./swiftbox.sh list
        which swift
        swiftc -v

    - name: Test Swift compiler
      run: |
        swift test.swift
        swiftc test.swift -o test && ./test

  test-amzn-nightly:
    container:
      image: amazonlinux:2
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --login -eo pipefail {0}
    steps:
    - name: Install tar and gzip
      run: yum install tar gzip -y

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test swiftbox version
      run: |
        chmod +x swiftbox.sh
        ./swiftbox.sh version
    
    - name: Test swiftbox lookup nightly
      run: ./swiftbox.sh lookup nightly

    - name: Test swiftbox get nightly
      run: ./swiftbox.sh get nightly

    - name: Install which
      run: yum install which -y

    - name: Test Swift status
      run: |
        echo "\$PATH=$PATH"
        ./swiftbox.sh list
        which swift
        swiftc -v

    - name: Test Swift compiler
      run: |
        source /etc/environment
        source /opt/swiftbox/env.sh
        swift test.swift
        swiftc test.swift -o test && ./test