name: CI

on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test swiftbox version
      run: |
        chmod +x swiftbox.sh
        ./swiftbox.sh version

    - name: Test swiftbox install
      run: ./swiftbox.sh install

    - name: Test swiftbox lookup
      run: swiftbox lookup 5.1.5

    - name: Test swiftbox get with sudo
      run: |
        sudo swiftbox get 5.1.2
        source /etc/environment
        source /etc/profile.d/swiftbox.sh
        which swift
        swiftc -v

    - name: Test swiftbox get
      run: |
        swiftbox get 5.2
        swiftbox get 5.1.5
        source /etc/environment
        source $HOME/.swiftbox/env.sh
        swiftc -v

    - name: Test swiftbox list and use
      run: |
        swiftbox list
        sudo swiftbox list
        swiftbox use 5.1.5
        swiftbox list
        source /etc/environment
        source $HOME/.swiftbox/env.sh
        swiftc -v

    - name: Test swiftbox clean
      run: |
        swiftbox clean
        sudo swiftbox clean

    - name: Test swiftbox remove
      run: |
        sudo swiftbox remove 5.1.2
        swiftbox remove 5.1.5
        swiftbox use 5.2

    - name: Test Swift status
      run: |
        source /etc/environment
        source $HOME/.swiftbox/env.sh
        echo "\$PATH=$PATH"
        which swift
        swiftc -v

    - name: Test Swift compiler
      run: |
        source /etc/environment  
        source $HOME/.swiftbox/env.sh
        swift test.swift
        swiftc test.swift -o test && ./test

    - name: Test swiftbox close
      run: swiftbox close

    - name: Test Swift disabled
      run: |
        source /etc/environment
        source $HOME/.swiftbox/env.sh
        if [ `which swift` != /usr/* ]
        then
          exit 1
        fi

  test-ubuntu-nightly:
    container:
      image: ubuntu:20.04
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test swiftbox version
      run: |
        chmod +x swiftbox.sh
        ./swiftbox.sh version

    - name: Test swiftbox lookup nightly
      run: ./swiftbox.sh lookup nightly

    - name: Test swiftbox get nightly
      env:
        DEBIAN_FRONTEND: noninteractive
        DEBCONF_NONINTERACTIVE_SEEN: true
      run: ./swiftbox.sh get nightly

    - name: Test Swift status
      shell: bash
      run: |
        source /etc/environment
        if [ -f $HOME/.swiftbox/env.sh ]
        then
          source $HOME/.swiftbox/env.sh
        fi
        if [ -f /opt/swiftbox/env.sh ]
        then
          source /opt/swiftbox/env.sh
        fi
        echo "\$PATH=$PATH"
        ./swiftbox.sh list
        which swift
        swiftc -v

    - name: Test Swift compiler
      shell: bash
      run: |
        source /etc/environment
        if [ -f $HOME/.swiftbox/env.sh ]
        then
          source $HOME/.swiftbox/env.sh
        fi
        if [ -f /opt/swiftbox/env.sh ]
        then
          source /opt/swiftbox/env.sh
        fi
        swift test.swift
        swiftc test.swift -o test && ./test

  test-centos-nightly:
    container:
      image: centos:8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install which
      run: yum install which -y

    - name: Test swiftbox version
      run: |
        chmod +x swiftbox.sh
        ./swiftbox.sh version
    
    - name: Test swiftbox lookup nightly
      run: ./swiftbox.sh lookup nightly

    - name: Test swiftbox get nightly
      run: ./swiftbox.sh get nightly

    - name: Test Swift status
      shell: bash
      run: |
        source /etc/environment
        if [ -f $HOME/.swiftbox/env.sh ]
        then
          source $HOME/.swiftbox/env.sh
        fi
        if [ -f /opt/swiftbox/env.sh ]
        then
          source /opt/swiftbox/env.sh
        fi
        echo "\$PATH=$PATH"
        ./swiftbox.sh list
        which swift
        swiftc -v

    - name: Test Swift compiler
      shell: bash
      run: |
        source /etc/environment
        if [ -f $HOME/.swiftbox/env.sh ]
        then
          source $HOME/.swiftbox/env.sh
        fi
        if [ -f /opt/swiftbox/env.sh ]
        then
          source /opt/swiftbox/env.sh
        fi
        swift test.swift
        swiftc test.swift -o test && ./test

  test-amzn-nightly:
    container:
      image: amazonlinux:2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install which
      run: yum install which -y

    - name: Test swiftbox version
      run: |
        chmod +x swiftbox.sh
        ./swiftbox.sh version
    
    - name: Test swiftbox lookup nightly
      run: ./swiftbox.sh lookup nightly

    - name: Test swiftbox get nightly
      run: ./swiftbox.sh get nightly

    - name: Test Swift status
      shell: bash
      run: |
        source /etc/environment
        if [ -f $HOME/.swiftbox/env.sh ]
        then
          source $HOME/.swiftbox/env.sh
        fi
        if [ -f /opt/swiftbox/env.sh ]
        then
          source /opt/swiftbox/env.sh
        fi
        echo "\$PATH=$PATH"
        ./swiftbox.sh list
        which swift
        swiftc -v

    - name: Test Swift compiler
      shell: bash
      run: |
        source /etc/environment
        if [ -f $HOME/.swiftbox/env.sh ]
        then
          source $HOME/.swiftbox/env.sh
        fi
        if [ -f /opt/swiftbox/env.sh ]
        then
          source /opt/swiftbox/env.sh
        fi
        swift test.swift
        swiftc test.swift -o test && ./test