name: Tag Version

on: [push]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Test swiftbox and update VERSION
      run: |
        chmod +x swiftbox.sh
        VERSION=`./swiftbox.sh version`
        if [ $? -eq 0 ]
        then
          if [ $VERSION = `cat VERSION` ]
          then
            exit 0
          else
            echo $VERSION > VERSION
            git config --global user.name  "${{ github.actor }}"
            git config --global user.email "`curl https://api.github.com/users/${{ github.actor }} | jq .email`"
            git commit -m "Release $VERSION" -a
            git tag -a "v$VERSION" -m "Release $VERSION"
          fi
        else
          exit 1
        fi
      shell: bash
        
    - name: Push to GitHub
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}